INSERT INTO
    image (imagePath)
VALUES
    ('argentina.png'),
    ('brazilie.png'),
    ('bulharsko.png'),
    ('cile.png'),
    ('cina.png'),
    ('dominikanskarepublika.png'),
    ('irak.png'),
    ('iran.png'),
    ('irsko.png'),
    ('italie.png'),
    ('jamajka.png'),
    ('jar.png'),
    ('kolumbie.png'),
    ('lotyssko.png'),
    ('lucembursko.png'),
    ('madarsko.png'),
    ('nemecko.png'),
    ('nigerie.png'),
    ('nizozemsko.png'),
    ('paraguay.png'),
    ('polsko.png'),
    ('severnikorea.png'),
    ('svedsko.png'),
    ('tunisko.png'),
    ('ukrajina.png');